import { defineStore } from 'pinia';

export const quizData = {
        tripGeneration: [
          {
            question: "What is the purpose of trip generation studies?",
            options: ["Measure travel demand", "Control traffic", "Improve road safety", "Reduce emissions"],
            correctAnswer: "Measure travel demand",
          },
          {
            question: "Which factor is most commonly used in trip generation analysis?",
            options: ["Land use", "Vehicle speed", "Pedestrian count", "Weather conditions"],
            correctAnswer: "Land use",
          },
          {
            question: "What is the purpose of a Cordon Count in traffic engineering?",
            options: [
              "To determine the total traffic activity inside an imaginary cordon, like a CBD.",
              "To determine traffic movement from one area to another as it crosses an imaginary screen.",
              "To determine the daily or seasonal variations in traffic volumes.",
              "To estimate the number of trips generated by a specific land use.",
              "To predict and track traffic volumes based on trip purpose."
            ],
            correctAnswer: "To determine the total traffic activity inside an imaginary cordon, like a CBD."
          },
          {
            "question": "According to the ITE Trip Generation Handbook, 3rd edition, what is the pass-by rate range for a supermarket in the PM peak hour?",
            "options": [
              "10% to 30%",
              "19% to 57%",
              "25% to 65%",
              "30% to 70%",
              "40% to 80%"
            ],
            "correctAnswer": "19% to 57%"
          },
          {
            "question": "What is the minimum left-turn storage lane length at an unsignalized intersection, assuming the peak hour truck traffic is less than 10%?",
            "options": [
              "1 vehicle length",
              "2 vehicle lengths",
              "3 vehicle lengths",
              "4 vehicle lengths",
              "5 vehicle lengths"
            ],
            "correctAnswer": "2 vehicle lengths"
          },
          {
            "question": "According to the Dublin significance criteria mentioned in the source, when is a project impact considered significant at a signalized intersection?",
            "options": [
              "When the project degrades the intersection LOS from C or better to LOS D or worse.",
              "When the project degrades the intersection LOS from D or better to LOS E or worse.",
              "When the project improves the intersection LOS from E or worse to LOS D or better.",
              "When the project improves the intersection LOS from F to LOS E.",
              "When the project maintains the existing intersection LOS."
            ],
            "correctAnswer": "When the project degrades the intersection LOS from D or better to LOS E or worse."
          },
          {
            "question": "According to the source, what is the average auto occupancy used in Problem 2.1?",
            "options": [
              "0.8",
              "0.9",
              "1.0",
              "1.1",
              "1.2"
            ],
            "correctAnswer": "1.0"
          },
          {
            "question": "In the context of traffic engineering, what does the acronym 'VMT' stand for?",
            "options": [
              "Vehicle Miles Traveled",
              "Vehicle Maintenance Time",
              "Volume Measurement Tool",
              "Virtual Mobility Test",
              "Variable Message Traffic"
            ],
            "correctAnswer": "Vehicle Miles Traveled"
          },
          {
            "question": "According to the ITE Trip Generation Manual, 10th Edition, what is the average vehicle occupancy for a high-turnover restaurant?",
            "options": [
              "1.5",
              "1.4",
              "1.6",
              "1.7",
              "1.8"
            ],
            "correctAnswer": "1.4"
          },
          {
            "question": "What is the minimum number of daily trips expected to be generated by a 1.25 million square foot shopping center, as per the source?",
            "options": [
              "10,000",
              "15,000",
              "20,000",
              "25,000",
              "30,000"
            ],
            "correctAnswer": "30,000"
          },
          {
            "question": "Which type of survey is used to determine cut-through traffic, as mentioned in the source?",
            "options": [
              "Radar speed survey",
              "License plate survey",
              "ADT counts",
              "Turning movement counts",
              "Household survey"
            ],
            "correctAnswer": "License plate survey"
          },
          {
            "question": "According to the source, what is a common criterion for justifying the installation of a traffic control device based on the number of correctable collisions in a calendar year?",
            "options": [
              "3",
              "4",
              "5",
              "6",
              "7"
            ],
            "correctAnswer": "5"
          },
          {
            "question": "In which situation is lane utilization of greatest concern, according to the source?",
            "options": [
              "Near a freeway interchange",
              "On approaches in the Central Business District where there is significant parking activity adjacent to the right lane",
              "Varying saturation flow rates in individual lanes on an approach",
              "The use of bus stops as informal right turn lanes",
              "All of the above"
            ],
            "correctAnswer": "Varying saturation flow rates in individual lanes on an approach"
          },
          {
            "question": "What is the primary determinant of traffic volume, as per the source?",
            "options": [
              "Day of the week",
              "Hour of the day",
              "Land use",
              "Weather conditions",
              "Traffic control devices"
            ],
            "correctAnswer": "Land use"
          },
          {
            "question": "What is the purpose of using Passenger Car Equivalents (PCE) in traffic engineering?",
            "options": [
              "To convert traffic flow into the peak 15 minutes.",
              "To account for the impact of different vehicle types on traffic flow.",
              "To convert weekday traffic volumes to Saturday and Sunday volumes.",
              "To determine the appropriate speed limit for a roadway.",
              "To calculate the number of lanes required for a given traffic volume."
            ],
            "correctAnswer": "To account for the impact of different vehicle types on traffic flow."
          },
          {
            "question": "Calculate the Peak Hour Factor (PHF) from the following two-hour count: 20, 30, 25, 40, 20, 55, 30, 25.",
            "options": [
              "0.72",
              "0.59",
              "0.55",
              "0.66",
              "0.80"
            ],
            "correctAnswer": "0.66"
          },
          {
            "question": "According to the California Highway Design Manual (HDM) 7th Edition, what is the appropriate bay taper length for a left turn lane in areas with restricted space and low speeds?",
            "options": [
              "30 feet",
              "60 feet",
              "90 feet",
              "120 feet",
              "150 feet"
            ],
            "correctAnswer": "90 feet"
          },
          {
            "question": "How is the Average Annual Weekday Traffic (AAWT) calculated, as per the ITE Transportation Planning Handbook, 4th Edition?",
            "options": [
              "Dividing total weekday traffic for the year by 250.",
              "Dividing total weekday traffic for the year by 260.",
              "Dividing total weekday traffic for the year by 270.",
              "Dividing total annual traffic by 365.",
              "Dividing total annual traffic by 7."
            ],
            "correctAnswer": "Dividing total weekday traffic for the year by 260."
          },
          {
            "question": "What is the main focus of TechTransfer, as described in the source?",
            "options": [
              "Conducting traffic impact studies for new developments.",
              "Providing transportation-related training and professional development.",
              "Developing new traffic control devices and technologies.",
              "Lobbying for transportation-related policies and regulations.",
              "Designing and constructing transportation infrastructure."
            ],
            "correctAnswer": "Providing transportation-related training and professional development."
          },
          {
            "question": "What is the California Traffic Engineer Exam Period, according to the source?",
            "options": [
              "September 3-12, 2024",
              "September 17-26, 2024",
              "October 14-28, 2024",
              "November 4-18, 2024",
              "December 2-16, 2024"
            ],
            "correctAnswer": "October 14-28, 2024"
          },
          {
            "question": "What does the source list as a key consideration for traffic control at internal intersections within a development?",
            "options": [
              "Short term VS long Term Parking",
              "Commercial delivery points",
              "Emergency Vehicle access",
              "Trash Pick up sites and access",
              "All of the above"
            ],
            "correctAnswer": "All of the above"
          },
          {
            "question": "What is the role of Trip Assignment in traffic impact analysis?",
            "options": [
              "Estimating the number of trips generated by a specific land use.",
              "Determining the distribution of trips among different destinations.",
              "Assigning trips to the transportation network based on their origins and destinations.",
              "Predicting the mode of transportation used for different trips.",
              "Evaluating the impact of traffic on the environment."
            ],
            "correctAnswer": "Assigning trips to the transportation network based on their origins and destinations."
          },
          {
            "question": "What is the purpose of the ITE Parking Generation Manual?",
            "options": [
              "To provide guidance on the design of parking facilities.",
              "To estimate the parking demand generated by different land uses.",
              "To analyze the impact of parking on traffic congestion.",
              "To develop parking regulations and policies.",
              "To evaluate the environmental impact of parking."
            ],
            "correctAnswer": "To estimate the parking demand generated by different land uses."
          },
          {
            "question": "What is the formula for calculating left-turn storage lane length at a signalized intersection, as per the HDM 7th Edition?",
            "options": [
              "Storage length = 0.5 to 1 x average # of vehicles/cycle arriving in LT lane",
              "Storage length = 1 to 1.5 x average # of vehicles/cycle arriving in LT lane",
              "Storage length = 1.5 to 2 x average # of vehicles/cycle arriving in LT lane",
              "Storage length = 2 to 2.5 x average # of vehicles/cycle arriving in LT lane",
              "Storage length = 2.5 to 3 x average # of vehicles/cycle arriving in LT lane"
            ],
            "correctAnswer": "Storage length = 1.5 to 2 x average # of vehicles/cycle arriving in LT lane"
          },
          {
            "question": "What are Diverted Linked Trips in the context of traffic impact analysis?",
            "options": [
              "Trips that are diverted from their usual route due to congestion or other factors.",
              "Trips that have one or more intermediate stops and are longer than one mile.",
              "Trips that are generated by a new development and did not exist before.",
              "Trips that are made by pedestrians or bicyclists.",
              "Trips that are made during peak hours."
            ],
            "correctAnswer": "Trips that have one or more intermediate stops and are longer than one mile."
          }
        ],
        parking: [
          {
            question: "What is the most common type of parking in urban areas?",
            options: ["On-street parking", "Underground parking", "Multilevel parking", "Valet parking"],
            correctAnswer: "On-street parking",
          },
          {
            question: "What is the key objective of parking management?",
            options: ["Maximize available spaces", "Minimize parking fees", "Increase vehicle speed", "Reduce parking duration"],
            correctAnswer: "Maximize available spaces",
          },
          {
            "question": "What is the purpose of the ITE Parking Generation Manual?",
            "options": [
              "To provide strict rules for parking design",
              "To offer guidance on estimating parking demand",
              "To dictate parking policies for all jurisdictions",
              "To set legal limits on parking space dimensions"
            ],
            "correctAnswer": "To offer guidance on estimating parking demand"
          },
          {
            "question": "Which of the following is NOT an example of shared parking?",
            "options": [
              "A church and a light industrial building using the same lot",
              "A shopping mall with its own dedicated parking garage",
              "On-street parking in a commercial area with time limits",
              "A public parking facility offering both short-term and long-term options"
            ],
            "correctAnswer": "A shopping mall with its own dedicated parking garage"
          },
          {
            "question": "According to the sources, what driver behavior is influenced by parking occupancy rates?",
            "options": [
              "Drivers are more likely to speed if parking is readily available",
              "Drivers perceive a lack of parking if occupancy exceeds 85%",
              "Drivers are more likely to use public transit if occupancy is below 50%",
              "Drivers are indifferent to occupancy rates, as long as they find a spot"
            ],
            "correctAnswer": "Drivers perceive a lack of parking if occupancy exceeds 85%"
          },
          {
            "question": "What is the benefit of 'unbundling' parking costs for rental units?",
            "options": [
              "It hides the true cost of parking from tenants",
              "It encourages tenants to own more vehicles",
              "It allows tenants to choose whether to pay for parking",
              "It simplifies rent collection for property managers"
            ],
            "correctAnswer": "It allows tenants to choose whether to pay for parking"
          },
          {
            "question": "Which of the following is NOT a common type of parking study?",
            "options": [
              "Parking inventory",
              "Parking usage studies",
              "Parking ticket analysis",
              "Accumulation and generation studies"
            ],
            "correctAnswer": "Parking ticket analysis"
          },
          {
            "question": "What is the standard width for an on-street parking space?",
            "options": [
              "6 feet",
              "8 feet",
              "10 feet",
              "12 feet"
            ],
            "correctAnswer": "8 feet"
          },
          {
            "question": "What color curb designates a loading zone for passengers?",
            "options": [
              "Red",
              "Yellow",
              "White",
              "Green"
            ],
            "correctAnswer": "White"
          },
          {
            "question": "What type of parking layout is generally considered more efficient for maximizing space?",
            "options": [
              "90-degree parking",
              "Angle parking",
              "Parallel parking",
              "Double parking"
            ],
            "correctAnswer": "Angle parking"
          },
          {
            "question": "What is the price elasticity of demand for parking?",
            "options": [
              "The change in parking supply relative to price changes",
              "The change in parking demand relative to price changes",
              "The total revenue generated from parking fees",
              "The fixed cost of providing parking spaces"
            ],
            "correctAnswer": "The change in parking demand relative to price changes"
          },
          {
            "question": "Which of the following is a benefit of using parking garages in urban areas?",
            "options": [
              "Increases traffic congestion on surrounding streets",
              "Reduces the need for on-street parking management",
              "Creates a perception of ample parking availability",
              "Encourages urban sprawl and longer commutes"
            ],
            "correctAnswer": "Creates a perception of ample parking availability"
          }
        ],
        signalTiming: [
          {
            question: "What is the purpose of signal timing plans?",
            options: ["Control vehicle flow", "Provide pedestrian safety", "Reduce congestion", "All of the above"],
            correctAnswer: "All of the above",
          },
          {
            question: "What is a signal cycle length?",
            options: ["The time it takes for all signals to return to the same state", "The distance between traffic signals", "The number of lanes at an intersection", "The speed of the vehicles through the intersection"],
            correctAnswer: "The time it takes for all signals to return to the same state",
          },
          {
            "question": "What does the acronym CA MUTCD stand for?",
            "options": [
              "California Motorist Uniform Traffic Control Devices",
              "California Manual on Uniform Traffic Control Devices",
              "California Manual on Unusual Traffic Control Devices",
              "California Manual on Urban Traffic Control Devices",
              "California Motorist Unusual Traffic Control Devices"
            ],
            "correctAnswer": "California Manual on Uniform Traffic Control Devices"
          },
          {
            "question": "Which of the following is NOT a purpose of a traffic control device?",
            "options": [
              "Promote safety",
              "Provide for orderly movement",
              "Notify drivers",
              "Generate revenue",
              "All of the above are purposes of traffic control devices"
            ],
            "correctAnswer": "Generate revenue"
          },
          {
            "question": "According to the CA MUTCD, what is the minimum size stop sign for a multi-lane approach?",
            "options": [
              "24\" x 24\"",
              "30\" x 30\"",
              "36\" x 36\"",
              "42\" x 42\"",
              "48\" x 48\""
            ],
            "correctAnswer": "36\" x 36\""
          },
          {
            "question": "What is the minimum size speed limit sign for a 40 mph multi-lane conventional highway?",
            "options": [
              "18\" x 24\"",
              "24\" x 30\"",
              "30\" x 36\"",
              "36\" x 48\"",
              "42\" x 48\""
            ],
            "correctAnswer": "30\" x 36\""
          },
          {
            "question": "Which sign is permitted to be posted above a stop sign?",
            "options": [
              "One-Way sign",
              "No Left Turn sign",
              "Right Turn Only sign",
              "Speed Limit sign",
              "None of the above"
            ],
            "correctAnswer": "One-Way sign"
          },
          {
            "question": "What is the minimum stop sign size for a two-lane approach that intersects a 50 mph speed limit?",
            "options": [
              "24\" x 24\"",
              "30\" x 30\"",
              "36\" x 36\"",
              "42\" x 42\"",
              "48\" x 48\""
            ],
            "correctAnswer": "36\" x 36\""
          },
          {
            "question": "How many No Right/Left Turn (R3-1/R3-2) signs are required at a minimum at an intersection of a two-way, two-lane road (one lane each direction)?",
            "options": [
              "1 sign near right/left",
              "1 sign far right/left",
              "2 signs near right and near left",
              "2 signs near right and far left",
              "The number of signs depends on the specific intersection geometry"
            ],
            "correctAnswer": "2 signs near right and far left"
          },
          {
            "question": "What is the minimum number of One-Way signs required at an intersection of a two-way, two-lane roadway with a one-way roadway?",
            "options": [
              "1",
              "2",
              "3",
              "4",
              "The number of signs depends on the specific intersection geometry"
            ],
            "correctAnswer": "4"
          },
          {
            "question": "What is the minimum distance in advance of a crosswalk should an advance crosswalk warning sign be placed for a road with a 45 mph speed limit?",
            "options": [
              "100 feet",
              "125 feet",
              "150 feet",
              "175 feet",
              "200 feet"
            ],
            "correctAnswer": "175 feet"
          },
          {
            "question": "According to the CA MUTCD, what is the minimum sign size for a Curve Warning (W1-1) on a single-lane conventional highway?",
            "options": [
              "24\" x 24\"",
              "30\" x 30\"",
              "36\" x 36\"",
              "42\" x 42\"",
              "The minimum size depends on the posted speed limit"
            ],
            "correctAnswer": "30\" x 30\""
          },
          {
            "question": "What is the minimum height at which a chevron alignment sign should be installed?",
            "options": [
              "3 feet",
              "4 feet",
              "5 feet",
              "6 feet",
              "7 feet"
            ],
            "correctAnswer": "4 feet"
          },
          {
            "question": "Which statement is TRUE regarding the placement of chevron signs?",
            "options": [
              "A minimum of two signs shall be installed on a curve or turn",
              "Chevron signs shall not be placed on the far side of a T-intersection facing the stem approach",
              "Chevron signs can be used to mark the ends of guardrails",
              "Chevron signs can be used to mark the ends of barriers",
              "All of the above statements are true"
            ],
            "correctAnswer": "Chevron signs shall not be placed on the far side of a T-intersection facing the stem approach"
          },
          {
            "question": "What is the recommended sign for a curve on a roadway with a 40 mph speed limit that has a 12-degree ball bank at 35 mph?",
            "options": [
              "W1-1 with a 35 mph advisory sign in advance and W1-6 or W1-8 at the curve",
              "W1-2 with a 35 mph advisory sign in advance and W1-6 or W1-8 at the curve",
              "W1-1 with a 35 mph advisory sign in advance of the curve",
              "W1-2 with a 35 mph advisory sign in advance of the curve",
              "No signs are required for this scenario"
            ],
            "correctAnswer": "W1-2 with a 35 mph advisory sign in advance of the curve"
          },
          {
            "question": "What is the maximum ball bank degree recommended for trucks and high-profile vehicles on curves?",
            "options": [
              "8 degrees",
              "9 degrees",
              "10 degrees",
              "11 degrees",
              "12 degrees"
            ],
            "correctAnswer": "10 degrees"
          },
          {
            "question": "Which of the following is NOT a pavement marking application?",
            "options": [
              "Centerlines",
              "Lane lines",
              "Edge lines",
              "Speed humps",
              "Crosswalks"
            ],
            "correctAnswer": "Speed humps"
          },
          {
            "question": "What type of pavement marking is most appropriate for guiding traffic through an intersection?",
            "options": [
              "Solid white line",
              "Solid yellow line",
              "Double solid yellow line",
              "Short dashed line",
              "Long dashed line"
            ],
            "correctAnswer": "Short dashed line"
          },
          {
            "question": "According to the CA MUTCD, who is responsible for traffic control plans (TCPs) for construction or maintenance projects?",
            "options": [
              "The contractor performing the work",
              "The engineer or designee of the public agency having jurisdiction",
              "The California Department of Transportation (Caltrans)",
              "The Federal Highway Administration (FHWA)",
              "The Occupational Safety and Health Administration (OSHA)"
            ],
            "correctAnswer": "The engineer or designee of the public agency having jurisdiction"
          },
          {
            "question": "For a construction zone on a 40 mph roadway, what is the recommended distance between advance lane warning signs?",
            "options": [
              "100 feet",
              "250 feet",
              "350 feet",
              "500 feet",
              "The distance varies depending on the type of construction activity"
            ],
            "correctAnswer": "250 feet"
          },
          {
            "question": "What is the length of a merging taper for a construction zone on a street with a 40 mph posted speed limit and a lane width of 14 feet, according to Caltrans Standard Plan T9?",
            "options": [
              "245 feet",
              "320 feet",
              "350 feet",
              "375 feet",
              "400 feet"
            ],
            "correctAnswer": "375 feet"
          },
          {
            "question": "Which sand barrel array should be used on a 45 mph roadway in advance of a 2-foot-wide K-rail with the same direction of traffic on both sides, according to Caltrans Standard Plan T1A?",
            "options": [
              "TU 11",
              "TU 14",
              "TU 17",
              "TU 21",
              "The appropriate array depends on the length of the K-rail"
            ],
            "correctAnswer": "TU 14"
          },
          {
            "question": "Which sand barrel array should be used on a 40 mph roadway in advance of a 2-foot-wide K-rail at the centerline of a roadway, according to Caltrans Standard Plan T1B?",
            "options": [
              "TU 11",
              "TU 14",
              "TB 11",
              "TB 14",
              "The appropriate array depends on the length of the K-rail"
            ],
            "correctAnswer": "TB 11"
          },
          {
            "question": "What type of arrow board is appropriate for use on low-speed urban streets, according to the CA MUTCD?",
            "options": [
              "Type A",
              "Type B (or II)",
              "Type C (or I)",
              "Type D",
              "The appropriate type depends on the visibility conditions"
            ],
            "correctAnswer": "Type A"
          },
          {
            "question": "What type of arrow board is intended for high-speed, high-volume motor vehicle traffic control projects, according to the CA MUTCD?",
            "options": [
              "Type A",
              "Type B (or II)",
              "Type C (or I)",
              "Type D",
              "The appropriate type depends on the visibility conditions"
            ],
            "correctAnswer": "Type C (or I)"
          },
          {
            "question": "What organization is responsible for developing the CA MUTCD?",
            "options": [
              "Federal Highway Administration (FHWA)",
              "National Highway Traffic Safety Administration (NHTSA)",
              "California Department of Transportation (Caltrans)",
              "Institute of Transportation Engineers (ITE)",
              "American Association of State Highway and Transportation Officials (AASHTO)"
            ],
            "correctAnswer": "Federal Highway Administration (FHWA)"
          }
        ],
      };
      
  
  

export const useDataStore = defineStore('data', {
    state: () => ({
        count: 0,
        detChannel: 1, // Default value
        // update all the below
        postedSpeed:25, 
        heading: 'NB', 
        phase: 'Phase 1',
        detName: '',
        detLatLon:'',
        hdData:'',
        quizQA:[],

    }),
    actions: {
        increment() {
            console.log("trying to count", this.count)
            this.count++;
        },
        checkMinValue() {
            console.log("trying to count", this.detChannel)
            if (this.detChannel < 1) {
              this.detChannel = 1;
            }
        },
        updateDetChannel(val) {
            if (val < 1) {
                this.detChannel = 1;
              } else {
                this.detChannel = val;
              }
        },
        updateSpeed(val){
            this.postedSpeed = val;
           
        }
    },
    //persist: true, // Optionally, add persistence
});