/**
 * YOLO dataset assembly: label lines, data.yaml, filename handling, the
 * deterministic train/val split, and dataset statistics.
 *
 * Framework free so it runs under `node --test`.
 *
 * The annotator is single-class by design, so every box is class 0 and the
 * class name only ever reaches data.yaml.
 */

import { clampRectToImage } from './annotatorGeometry.js';
import { fnv1a32 } from './hash.js';

export const DEFAULT_CLASS_NAME = 'traffic_signal';
export const LABEL_PRECISION = 6;

/** Boxes that clamp below this many image pixels are dropped at export. */
export const MIN_EXPORT_PX = 1;

/**
 * One YOLO label line: `class cx cy w h`, normalized to the image.
 *
 * The rect is clamped in image space *before* normalizing. Clamping the four
 * normalized values independently does not guarantee cx +/- w/2 stays inside
 * [0,1] and can emit a box that hangs off the edge of its own image.
 */
export function toYoloLine(box, imgW, imgH, { classId = 0, precision = LABEL_PRECISION } = {}) {
  const rect = clampRectToImage(box, imgW, imgH);
  if (rect.w < MIN_EXPORT_PX || rect.h < MIN_EXPORT_PX) return null;

  const cx = (rect.x + rect.w / 2) / imgW;
  const cy = (rect.y + rect.h / 2) / imgH;
  const w = rect.w / imgW;
  const h = rect.h / imgH;

  return [classId, cx, cy, w, h]
    .map((value, index) => (index === 0 ? String(value) : value.toFixed(precision)))
    .join(' ');
}

/**
 * The .txt for one image. A reviewed image with no boxes yields an empty
 * string — a zero-byte file, not a bare newline, because some tooling treats a
 * whitespace-only label file as malformed rather than as a negative sample.
 */
export function buildLabelFile(boxes, imgW, imgH, options = {}) {
  const lines = [];
  let dropped = 0;
  for (const box of boxes || []) {
    const line = toYoloLine(box, imgW, imgH, options);
    if (line) lines.push(line);
    else dropped += 1;
  }
  return { text: lines.length ? `${lines.join('\n')}\n` : '', dropped, kept: lines.length };
}

/**
 * Class names are restricted to a plain identifier so data.yaml never needs
 * YAML quoting, and because a class name with spaces is a bad idea downstream.
 */
export function sanitizeClassName(name) {
  const cleaned = String(name == null ? '' : name)
    .trim()
    .replace(/[^A-Za-z0-9_-]+/g, '_')
    .replace(/^_+|_+$/g, '');
  return cleaned || DEFAULT_CLASS_NAME;
}

export function buildDataYaml(className = DEFAULT_CLASS_NAME, { hasTest = false } = {}) {
  const name = sanitizeClassName(className);
  return [
    '# Generated by Traffic Signal Kit - YOLO Image Annotator',
    '# https://trafficsignalkit.com/yolo-image-annotator',
    'path: .',
    'train: images/train',
    'val: images/val',
    // `test` is optional in the Ultralytics schema, so it is only written when
    // a test split was actually produced.
    ...(hasTest ? ['test: images/test'] : []),
    'nc: 1',
    'names:',
    `  0: ${name}`,
    '',
  ].join('\n');
}

export function splitExtension(filename) {
  const name = String(filename || '');
  const dot = name.lastIndexOf('.');
  if (dot <= 0) return { base: name, ext: '' };
  return { base: name.slice(0, dot), ext: name.slice(dot).toLowerCase() };
}

export function sanitizeBasename(filename) {
  const { base } = splitExtension(filename);
  const cleaned = base
    .replace(/[^A-Za-z0-9._-]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^[-.]+|[-.]+$/g, '');
  return cleaned || 'image';
}

/**
 * Unique basenames across the whole selection.
 *
 * Two folders of `frame001.png` would otherwise collide inside the zip, so one
 * image and its labels would silently overwrite the other and halve the
 * dataset without any visible error.
 */
export function dedupeBasenames(filenames) {
  const seen = new Map();
  return (filenames || []).map((filename) => {
    const base = sanitizeBasename(filename);
    const count = seen.get(base) || 0;
    seen.set(base, count + 1);
    return count === 0 ? base : `${base}-${count + 1}`;
  });
}

/**
 * Strips a trailing frame index so burst frames from one video share a group.
 * `Main-St-Frame-142` and `Main-St-Frame-143` both reduce to `Main-St`.
 */
export function deriveGroupKey(basename) {
  const stripped = String(basename || '').replace(/[-_ ]*(frame|img|image|shot)?[-_ ]*\d+$/i, '');
  return stripped || String(basename || '');
}

export const SPLITS = ['train', 'val', 'test'];

/**
 * Hash-based split assignment.
 *
 * Hashing the name instead of shuffling gives the property that matters:
 * adding 50 images next week does not reshuffle the 200 already assigned, so
 * two models trained a week apart remain comparable. The cost is that the
 * ratios are approximate, which the UI compensates for by reporting the counts
 * actually achieved.
 *
 * The three splits are contiguous bands over the same hash fraction:
 *
 *   0 ......... valRatio ......... valRatio+testRatio ......... 1
 *   |<-- val -->|<---- test ----->|<-------- train -------->|
 *
 * Val sits first so that a dataset built with testRatio = 0 gets byte-for-byte
 * the same assignments it did before test splits existed.
 */
export function splitFor(key, { valRatio = 0.2, testRatio = 0 } = {}, seed = '') {
  const val = Math.max(0, Math.min(1, Number(valRatio) || 0));
  const test = Math.max(0, Math.min(1 - val, Number(testRatio) || 0));
  if (val <= 0 && test <= 0) return 'train';

  const fraction = fnv1a32(`${seed}|${key}`) / 0x100000000;
  if (fraction < val) return 'val';
  if (fraction < val + test) return 'test';
  return 'train';
}

export function assignSplits(basenames, { valRatio = 0.2, testRatio = 0, seed = '', groupSplit = true } = {}) {
  const assign = new Map();
  const counts = { train: 0, val: 0, test: 0 };
  for (const base of basenames || []) {
    const key = groupSplit ? deriveGroupKey(base) : base;
    const split = splitFor(key, { valRatio, testRatio }, seed);
    assign.set(base, split);
    counts[split] += 1;
  }
  return { assign, counts };
}

/** Counts that drive the progress line and the export warnings. */
export function datasetStats(images, { warnBelowPx = 8 } = {}) {
  const stats = {
    total: 0,
    annotated: 0,
    negative: 0,
    pending: 0,
    boxes: 0,
    tiny: 0,
  };
  for (const image of images || []) {
    stats.total += 1;
    const boxCount = (image.boxes || []).length;
    stats.boxes += boxCount;
    for (const box of image.boxes || []) {
      if (box.w < warnBelowPx || box.h < warnBelowPx) stats.tiny += 1;
    }
    if (!image.reviewed) stats.pending += 1;
    else if (boxCount > 0) stats.annotated += 1;
    else stats.negative += 1;
  }
  return stats;
}

/**
 * The images that belong in the dataset.
 *
 * Unreviewed images are excluded unless explicitly opted in: exporting them as
 * negatives would teach the detector that traffic signals are background, and
 * the damage is invisible until the model underperforms.
 */
export function selectExportImages(images, { includeUnreviewed = false } = {}) {
  return (images || []).filter((image) => image.reviewed || includeUnreviewed);
}

export function buildReadme({ className, counts, stats, generatedAt = new Date() }) {
  return [
    'YOLO dataset generated by Traffic Signal Kit',
    'https://trafficsignalkit.com/yolo-image-annotator',
    '',
    `Generated:   ${generatedAt.toISOString()}`,
    `Class:       0 = ${sanitizeClassName(className)}`,
    `Images:      ${counts.train + counts.val + (counts.test || 0)} (${counts.train} train / ${counts.val} val${
      counts.test ? ` / ${counts.test} test` : ''
    })`,
    `Boxes:       ${stats.boxes}`,
    `Negatives:   ${stats.negative} (reviewed images with no signals, exported as empty .txt)`,
    '',
    'Labels are normalized: class cx cy w h, one line per box, relative to the',
    'image size. Images are the original files, copied byte for byte.',
    '',
    'annotations-project.json can be loaded back into the annotator to keep',
    'editing, once you re-select the same image files.',
    '',
  ].join('\n');
}
